-- MySQL Script generated by MySQL Workbench
-- Mon Oct 26 08:27:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sena_lab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sena_lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sena_lab` DEFAULT CHARACTER SET utf8 ;
USE `sena_lab` ;

-- -----------------------------------------------------
-- Table `sena_lab`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'Este campo permite identificar el tipo de usuario(rol) si es administrador o empleado.',
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`Tipo_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Tipo_Contrato` (
  `idTipo_Contrato` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `tipo_contrato` VARCHAR(45) NOT NULL COMMENT 'Tipo de contrato con el que cuenta el usuario, fijo, indefinido, por horas, obra o labor, aprendizaje, ',
  PRIMARY KEY (`idTipo_Contrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`Certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Certificado` (
  `idCertificado` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `encabezado` VARCHAR(45) NOT NULL COMMENT 'Datos de referencia de la empresa que esta generando el certificado.',
  `texto` VARCHAR(200) NOT NULL COMMENT 'Este campo trae la infromación que hace referencia a la certificación laboral que esta expidiendo el usuario, de acuerdo a su necesidad',
  PRIMARY KEY (`idCertificado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`Incapacidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Incapacidades` (
  `idIncapacidades` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `nombres` VARCHAR(45) NOT NULL COMMENT 'Nombre del usuario',
  `apellidos` VARCHAR(45) NOT NULL COMMENT 'Apellido del usuario',
  `tipo_documento` VARCHAR(45) NOT NULL COMMENT 'Este campo determina el tipo de docummento que esta relacionado con el usuario',
  `numero_documento` VARCHAR(45) NOT NULL COMMENT 'Número de identificación asociado al usuario',
  `correo` VARCHAR(45) NOT NULL COMMENT 'Correo electronico asociado al usuario, y con el cual inicio la sesión',
  `nombre_eps` VARCHAR(45) NOT NULL COMMENT 'Nombre de la EPS asociada al usuario y a la cual esta afiliado en la actualidad. ',
  `no_orden` VARCHAR(45) NOT NULL COMMENT 'Este campo guarda el número de consecutivo de la incapacidad que esta impresa en la que expide la eps, para llevar control y que al auditar se pueda saber si el empleado repitio o no de incapacidad. ',
  `dias_incapacidad` INT(10) NOT NULL COMMENT 'En este campo se va a guardar los días de incapacidad otorgados por la EPS',
  `fecha_inicio` VARCHAR(45) NOT NULL COMMENT 'Campo que almacena la fecha de inicio de la incapacidad',
  `fecha_terminacion` VARCHAR(45) NOT NULL COMMENT 'Fecha de terminación de la incapacidad otorgada por la EPS',
  `tipo_incapacidad` VARCHAR(45) NOT NULL COMMENT 'Este campo guardara el tipo de incapacidad que sera otrogada por la EPS. ',
  `Genero_idGenero` INT NOT NULL COMMENT 'Lleve foranea asociada a la tabla Genero, donde se determina si es hombre o mujer',
  `Rol_idRol` INT NOT NULL COMMENT 'Llave foranea asociada a la tabla Rol, con la cual se validara si es empleado o administrador',
  PRIMARY KEY (`idIncapacidades`),
  INDEX `fk_Incapacidades_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Incapacidades_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `sena_lab`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`usuarios` (
  `id` INT(11) NOT NULL,
  `nombre` TEXT NOT NULL,
  `usuario` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `perfil` TEXT NOT NULL,
  `foto` TEXT NOT NULL,
  `estado` INT(11) NOT NULL,
  `ultimo_login` DATETIME NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `Incapacidades_idIncapacidades` INT NOT NULL,
  `Certificado_idCertificado` INT NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_Incapacidades1_idx` (`Incapacidades_idIncapacidades` ASC) VISIBLE,
  INDEX `fk_usuarios_Certificado1_idx` (`Certificado_idCertificado` ASC) VISIBLE,
  INDEX `fk_usuarios_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_Incapacidades1`
    FOREIGN KEY (`Incapacidades_idIncapacidades`)
    REFERENCES `sena_lab`.`Incapacidades` (`idIncapacidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_Certificado1`
    FOREIGN KEY (`Certificado_idCertificado`)
    REFERENCES `sena_lab`.`Certificado` (`idCertificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `sena_lab`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `sena_lab`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `Tipo_Contrato_idTipo_Contrato` INT NOT NULL,
  `Certificado_idCertificado` INT NOT NULL,
  `usuarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`idContrato`),
  INDEX `fk_Contrato_Tipo_Contrato1_idx` (`Tipo_Contrato_idTipo_Contrato` ASC) VISIBLE,
  INDEX `fk_Contrato_Certificado1_idx` (`Certificado_idCertificado` ASC) VISIBLE,
  INDEX `fk_Contrato_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contrato_Tipo_Contrato1`
    FOREIGN KEY (`Tipo_Contrato_idTipo_Contrato`)
    REFERENCES `sena_lab`.`Tipo_Contrato` (`idTipo_Contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Certificado1`
    FOREIGN KEY (`Certificado_idCertificado`)
    REFERENCES `sena_lab`.`Certificado` (`idCertificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sena_lab`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `nombre_empresa` VARCHAR(45) NOT NULL COMMENT 'Nombre de la empresa',
  `direccion_empresa` VARCHAR(45) NOT NULL COMMENT 'Dirección de la empresa ',
  `nit_empresa` VARCHAR(45) NOT NULL COMMENT 'Número de indentificación de la empresa',
  `telefono_empresa` VARCHAR(45) NOT NULL COMMENT 'Teléfono de la empresa',
  `usuarios_id` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  INDEX `fk_Empresa_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sena_lab`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`Empresa_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Empresa_Contrato` (
  `Empresa_idEmpresa` INT NOT NULL,
  `Contrato_idContrato` INT NOT NULL,
  PRIMARY KEY (`Empresa_idEmpresa`, `Contrato_idContrato`),
  INDEX `fk_Empresa_has_Contrato_Contrato1_idx` (`Contrato_idContrato` ASC) VISIBLE,
  INDEX `fk_Empresa_has_Contrato_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Empresa_has_Contrato_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `sena_lab`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empresa_has_Contrato_Contrato1`
    FOREIGN KEY (`Contrato_idContrato`)
    REFERENCES `sena_lab`.`Contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sena_lab`.`Especificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sena_lab`.`Especificaciones` (
  `idEspecificaciones` INT NOT NULL AUTO_INCREMENT COMMENT 'Llave primaria que permite enlazar con las otras tablas de la base de datos.',
  `tipo_especificacion` VARCHAR(45) NOT NULL COMMENT 'Este campo determina el tipo de especificación de la certificación, con salario, sin salario, si es de planta o no, cargo, fecha, ',
  `Certificado_idCertificado` INT NOT NULL COMMENT 'Llave foranea asociada a la tabla Certificado',
  PRIMARY KEY (`idEspecificaciones`),
  INDEX `fk_Especificaciones_Certificado1_idx` (`Certificado_idCertificado` ASC) VISIBLE,
  CONSTRAINT `fk_Especificaciones_Certificado1`
    FOREIGN KEY (`Certificado_idCertificado`)
    REFERENCES `sena_lab`.`Certificado` (`idCertificado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
